ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>',views.full_remove,name='full_remove')
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecommerceproject/shop/urls.py
from django.urls import path

from . import views
app_name='shop'

urlpatterns = [
    path('',views.allProCat,name='allProCat'),
    path('<slug:c_slug>/',views.allProCat,name="product_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name="prodcatDetail"),
]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    Product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.Product)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    Product=product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(Product=Product,cart=cart)
        if cart_item.quantity < cart_item.Product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            Product=Product,
            quantity=1,
            cart=cart

        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.Product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    Product=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(Product=Product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()

    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(Product=Product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body style="background-color:rgb(180, 180, 180)" class="d-flex flex-column min-vh-100">
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block body %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        this is the cart page. procced to review your items and place the order


{% endblock %}

{% block title %}
    cart- WE SHOP company pvt ltd
{% endblock %}
{% block body %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            your shopping cart ios empty
        </h1>
            <br>
            <p class="text-center"> please click<a href="{% url 'shop:allProCat' %}">here</a>to continue shopping</p>
    </div>

</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="#"><img src="{{cart_item.Product.image.url}}" alt="" width="100px" height="100px" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-lef">{{cart_item.Product.name}}
                    <br>
                    SKU: {{cart_item.Product.id}}
                    <br>
                    price: $ {{cart_item.Product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                   $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.Product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.Product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                   <a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    <a href="{% url 'cart:full_remove' cart_item.Product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    $nbsp;<a href="{% url 'cart:cart_remove' cart_item.Product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    $nbsp;<a href="{% url 'cart:full_remove' cart_item.Product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before procceding with the order payment.

                </td>
            </tr>
            <tr>
                <td class="text-left">
                   <b> your total is <strong>{{total}}/-</strong></b>

                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProCat' %}" class="btn btn-secondary btn-block my_custom_button">continue shopping</a>
        </div>

        <div class="mx-auto">
            <a href="{% url 'shop:allProCat' %}" class="btn btn-success">pay now</a>
        </div>


    </div>

</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        well come WE SHOP where you can buy differend items....
    {% endif %}
{% endblock %}



{% block title %}
    {% if category %}
        {{category.name}} - WE SHOP
    {% else %}
        see our new collection - WE SHOP
    {% endif %}
{% endblock %}



{% block body %}
    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a href="{% url 'shop:allProCat'%}">our product collection </a></p>
            </div>
            </div>
        </div>
    {% endif %}
 <div class="mx_auto">
     {% if category %}
     <img class="my_image" src="{{category.image.url}}"  alt="{{category.name}}">
 </div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1300px" height="400px">
</div>
<br>
<div>
    <h1 class="text-center my_title">our product collection</h1>
    <p class="text-justify">Online shopping site in India - Shop Online for men, women and kids fashion, home décor and furnishings, kitchen apppliances, health and sports products at best prices from ShopClues. Easy</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4" style="margin-bottom:20px">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" height="300px" width="50px" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>${{product.price}}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

       <hr>
        <div class="text-center">
            {% for  pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<footer class="mt-auto">
<div  class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;weshop tech pvt ltd.All rights Reserved</p>
</div>
</footer>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'shop:allProCat' %}" ><img src="{% static 'img/logo.png' %}" alt="logimage" height="100px" width="100px">
    </center>
</header>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProCat' %}">All Product</a></li>
                    {% for cat in links %}

            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                    {% endfor %}

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail'%}" ><i class="fa fa-shopping-cart">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        {{ product.description|truncatewords:155 }}

{% endblock %}



{% block title %}
    {% if category %}
        {{product.name}} - WE SHOP

    {% endif %}
{% endblock %}



{% block body %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'shop:allProCat' %}">Home</a> |<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </p>

    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_titile">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_prod_titile">PRODUCT DESCRIPTION</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">add to cart</a>
            {% endif %}
        </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        we have variety of products

{% endblock %}

{% block title %}
    search
{% endblock %}
{% block body %}

<div>
    <p class="text-center my_search_text">you have seached for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4" style="margin-bottom:20px">
                <div class="card text-center" style="min-width:18rem;">
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" height="300px" width="50px" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>${{product.price}}</p>
                    </div>
                </div>
            </div>

        {% empty %}
        <div class="row mx-auto">
        <p class="text-center my_search_text">0 result found</p>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}